fs=20;
t=-(1/fs)*40:1/fs:(1/fs)*40;
f=0.5;
subplot(3,3,1);
a=sin(2*pi*f*t);
stem(t,a,'k');
title('Sine Wave');
ylabel('Amplitude');
xlabel('Time[n]');
subplot(3,3,2);
b=cos(2*pi*f*t);
stem(t,b,'k');
title(' Cosine Wave');
ylabel('Amplitude');
xlabel('Time[n]');
subplot(3,3,3);
c=sinc(2*pi*f*t);
stem(t,c,'k');
title('Sinc Wave');
ylabel('Amplitude');
xlabel('Time[n]');
subplot(3,3,4);
a= t==0;
stem(t,a,'k');
title('Unit Impulse Signal');
ylabel('Amplitude');
xlabel('Time[n]');
subplot(3,3,5);
unitstep = t>=0;
stem(t,unitstep,'k');
title('Unit Step Signal');
ylabel('Amplitude');
xlabel('Time[n]');
subplot(3,3,6);
d= abs(t)<1;
d=d.*(1-abs(t));
stem(t,d,'k');
title('Triangular Signal');
ylabel('Amplitude');
xlabel('Time[n]');
subplot(3,3,7);
ramp = t.*unitstep;
stem(t,ramp,'k');
title('Ramp Signal');



ylabel('Amplitude');							    
xlabel('Time[n]');								
subplot(3,3,8);
rect= abs(t)<0.5;
stem(t,rect,'k');
title('Rectangular Signal');
ylabel('Amplitude');
xlabel('Time[n]');
subplot(3,3,9);
expone=exp(t);
stem(t,expone,'k');
title('Exponential Signal');
ylabel('Amplitude');
xlabel('Time[n]');
